(define (make-point x y) (cons x y))
(define (x-point p) (car p))
(define (y-point p) (cdr p))
(define (print-point p)
  (newline)
  (display "(")
  (display (x-point p))
  (display ",")
  (display (y-point p))
  (display ")"))

(define (make-segment p q) (cons p q))
(define (start-segment s) (car s))
(define (end-segment s) (cdr s))
(define (midpoint-segment s)
  (make-point (/ (+ (x-point (start-segment s))
                    (x-point (end-segment s)))
                 2.0)
              (/ (+ (y-point (start-segment s))
                    (y-point (end-segment s)))
                 2.0)))

(define p (make-point 2.3 5.7))
(define q (make-point 11.13 17.19))
(define s (make-segment p q))
(print-point (midpoint-segment s))
